language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexandre84rj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexandre84rj/react-test npm test

after_success: 
  - docker build -t alexandre84rj/multi-client ./client
  - docker build -t alexandre84rj/multi-nginx ./nginx
  - docker build -t alexandre84rj/multi-server ./server
  - docker build -t alexandre84rj/multi-worker ./worker
  #Login Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  #Pegue as imagens e push para o Docker Hub  
  - docker push alexandre84rj/multi-client
  - docker push alexandre84rj/multi-nginx
  - docker push alexandre84rj/multi-server
  - docker push alexandre84rj/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-995967466921
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY